GET http://localhost:3000/api/category/24
Accept: application/json
Content-type: application/json


###
GET http://localhost:3000/api/product/119
Accept: application/json
Content-type: application/json



###
POST https://api.bigcommerce.com/stores/sn8rz5r2c0/v3/customers/attributes
X-Auth-Token: ih9gyqqu3cmkqe3ocq0lrfwde79uzl1
Accept: application/json
Content-type: application/json
 
[
  {
    "name": "Clubs",
    "type": "string"
  }
]

###
POST https://api.bigcommerce.com/stores/ool39ii0tw/v3/storefront/api-token
X-Auth-Token: h52k4mds7n8cn4l195nuof00k0drpcu
Accept: application/json
Content-type: application/json

{
  "channel_id": 1,
  "expires_at": 1672491599
}

###
GET https://api.bigcommerce.com/stores/ool39ii0tw/v3/customers/attribute-values
X-Auth-Token: h52k4mds7n8cn4l195nuof00k0drpcu
Accept: application/json
Content-type: application/json
###
GET https://api.bigcommerce.com/stores/ool39ii0tw/v3/catalog/categories/24
X-Auth-Token: h52k4mds7n8cn4l195nuof00k0drpcu
Accept: application/json
Content-type: application/json

###
POST https://uniform5.mybigcommerce.com/graphql
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJjaWQiOjEsImNvcnMiOltdLCJlYXQiOjE2NzI0OTE1OTksImlhdCI6MTYzMTcwMDQ3MiwiaXNzIjoiQkMiLCJzaWQiOjEwMDIwMDY3NTMsInN1YiI6ImVyMnhmM3NxdWNreWRoYm92YXRwa3cxZWpkMWJ6NHoiLCJzdWJfdHlwZSI6MiwidG9rZW5fdHlwZSI6MX0.FNaQ3gLjzq8zhwX6xqZ_tvb0LGs3qwISqivOa0axV4WSSDYB-thCiPL0VJHftF0PTPnCScg-_Vvs0CRVeI4OvQ
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation Login($email: String!, $pass: String!) {
  login(email: $email, password: $pass) {
    result
    customer {
      entityId
      firstName
      lastName
      company
      email
      customerGroupId
      attributes {
        attribute(entityId:1) {
          name
          value
        }
      }
    }
  }
}

{"email": "simon.pallister+rugby@bigcommerce.com", "pass": "Password.123"}